services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: local_feature_flag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network

  backend:
    build:
      context: ../
      dockerfile: ./docker/go/Dockerfile

    container_name: backend

    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres_network


volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
